import React from 'react';
import { 
  Mic, 
  Video as VideoIcon, 
  FileText, 
  BarChart2, 
  Video, 
  Globe, 
  MessageCircle, 
  LayoutList, 
  Users, 
  Smartphone, 
  Zap, 
  TrendingUp, 
  Code, 
  Calculator, 
  Percent, 
  Search, 
  Sparkles, 
  Repeat, 
  Activity, 
  Clock
} from 'lucide-react';

export type Category = 'All' | 'Business' | 'Social' | 'Finance' | 'Education' | 'Engineering' | 'Marketing';
export type AccessLevel = 'All' | 'Free' | 'Paid';
export type ToolStatus = 'All' | 'Active' | 'Coming Soon';

export interface Tool {
  id: string;
  name: string;
  tagline: string;
  description: string;
  pain: string;
  logic: string;
  category: Category;
  icon: React.ReactNode;
  keywords: string[];
  status: 'Active' | 'Coming Soon';
  savings: string;
  protocol: string;
  model?: string;
  cost: string;
  latency: string;
  depth: string;
  isFree?: boolean;
  usageCount?: number;
  isTrending?: boolean;
}

export const toolsData: Tool[] = [
  {
    id: 'voice-to-text',
    name: 'Voice to Text',
    tagline: 'Record voice or upload audio',
    description: 'Convert any audio file into clean, formatted text with easy-to-read timestamps.',
    pain: 'Hours spent manually transcribing audio for blogs and research.',
    logic: 'High-accuracy voice recognition using the latest AI technology.',
    category: 'Social',
    icon: <Mic size={20} />,
    keywords: ['transcribe', 'voice', 'audio', 'ai'],
    status: 'Active',
    savings: '1h per file',
    protocol: 'Smart-Scribe',
    model: 'AI Voice V3',
    cost: 'FREE',
    latency: 'Instant',
    depth: 'High Accuracy',
    usageCount: 4500,
    isTrending: true,
    isFree: true
  },
  {
    id: 'instagram-transcript',
    name: 'Reels Text Extractor',
    tagline: 'Get text from Instagram Reels',
    description: 'Paste any Instagram link to get the text from the video quickly for easy repurposing.',
    pain: 'Watching reels 10x to write down notes for content creation.',
    logic: 'Reads video audio and converts it to searchable text instantly.',
    category: 'Social',
    icon: <VideoIcon size={20} />,
    keywords: ['instagram', 'reels', 'transcript', 'social'],
    status: 'Active',
    savings: '10m per reel',
    protocol: 'Social-Link-Extract',
    model: 'Reel-Reader-AI',
    cost: 'FREE',
    latency: '2.5s',
    depth: 'Full Text Scan',
    usageCount: 3200,
    isTrending: true,
    isFree: true
  },
  {
    id: 'proposal-generator',
    name: 'Proposal Maker',
    tagline: 'Win more clients easily',
    description: 'Create professional business proposals with data and pricing help to close deals faster.',
    pain: "Hours spent on formatting and guessing the right price.",
    logic: 'Creates persuasive proposals based on successful industry standards.',
    category: 'Business',
    icon: <FileText size={20} />,
    keywords: ['freelance', 'sales', 'pitch'],
    status: 'Coming Soon',
    savings: '6h saved',
    protocol: 'Sales-Pro-Logic',
    model: 'Business AI',
    cost: '$1.00',
    latency: 'Fast',
    depth: 'Pro Templates',
    usageCount: 1240,
    isTrending: true
  },
  {
    id: 'startup-validator',
    name: 'Business Idea Checker',
    tagline: 'See if your idea will work',
    description: 'Turns your idea into a complete report with market and competitor research.',
    pain: "Months of building products that nobody actually wants.",
    logic: 'Analyzes market trends and competitors to see if an idea is viable.',
    category: 'Business',
    icon: <BarChart2 size={20} />,
    keywords: ['startup', 'entrepreneur', 'research'],
    status: 'Coming Soon',
    savings: '40h research',
    protocol: 'Market-Check',
    model: 'Research Engine',
    cost: '$1.00',
    latency: 'Deep Scan',
    depth: 'Global Markets',
    usageCount: 850,
    isTrending: true
  },
  {
    id: 'video-auditor',
    name: 'Social Video Checker',
    tagline: 'Improve your video views',
    description: 'Checks your video hooks and pace to help you get more views on social media.',
    pain: "Posting videos that fail to get views or engagement.",
    logic: 'Analyzes top performing videos to give you tips on better hooks.',
    category: 'Social',
    icon: <Video size={20} />,
    keywords: ['reels', 'tiktok', 'shorts'],
    status: 'Coming Soon',
    savings: '4h saved',
    protocol: 'Trend-Check',
    model: 'Viral-AI',
    cost: '$1.00',
    latency: 'Fast',
    depth: 'Top 1% Analysis',
    usageCount: 2100,
    isTrending: true
  },
  {
    id: 'domain-finder',
    name: 'Website Name Finder',
    tagline: 'Find the perfect domain name',
    description: 'Search for available website names and check for trademarks easily.',
    pain: "Wasting days searching for available website names.",
    logic: 'Checks availability and trademark issues in real-time.',
    category: 'Business',
    icon: <Globe size={20} />,
    keywords: ['branding', 'domain', 'launch'],
    status: 'Coming Soon',
    savings: '2h saved',
    protocol: 'Brand-Search',
    model: 'Domain AI',
    cost: '$1.00',
    latency: 'Instant',
    depth: 'Full Check'
  },
  {
    id: 'tweet-generator',
    name: 'Social Post Generator',
    tagline: 'Write better social posts',
    description: 'Get ideas for posts by looking at what is trending right now on social media.',
    pain: "Staring at a blank screen trying to come up with ideas.",
    logic: 'Finds trending topics and helps you write engaging hooks.',
    category: 'Social',
    icon: <MessageCircle size={20} />,
    keywords: ['social', 'marketing', 'twitter'],
    status: 'Coming Soon',
    savings: '2h saved',
    protocol: 'Post-Logic',
    model: 'Engagement AI',
    cost: '$1.00',
    latency: 'Instant',
    depth: 'Trend Search',
    usageCount: 1800,
    isTrending: true
  },
  {
    id: 'scope-killer',
    name: 'Task List Maker',
    tagline: 'Break projects into simple tasks',
    description: 'Turns simple project ideas into detailed lists of what needs to be done.',
    pain: "Small requests turning into massive projects without clear plans.",
    logic: 'Automatically identifies hidden steps in your project ideas.',
    category: 'Business',
    icon: <LayoutList size={20} />,
    keywords: ['agile', 'srs', 'freelance'],
    status: 'Coming Soon',
    savings: '3h saved',
    protocol: 'Task-Plan',
    model: 'Project AI',
    cost: '$1.00',
    latency: 'Instant',
    depth: 'Detailed Step-by-Step',
    usageCount: 450
  },
  {
    id: 'talent-scalpel',
    name: 'Resume Scanner',
    tagline: 'Find the best people for the job',
    description: 'Scans resumes and tells you who has the best skills for your project.',
    pain: 'Reading hundreds of resumes manually and missing good candidates.',
    logic: 'Matches resume skills against your specific project needs.',
    category: 'Business',
    icon: <Users size={20} />,
    keywords: ['hr', 'recruiting', 'cv'],
    status: 'Coming Soon',
    savings: '12h saved',
    protocol: 'Talent-Scan',
    model: 'Hiring AI',
    cost: '$1.00',
    latency: 'Deep Scan',
    depth: 'Skill Match',
    usageCount: 920
  },
  {
    id: 'profile-architect',
    name: 'Profile Optimizer',
    tagline: 'Get more leads from your profile',
    description: 'Helps you improve your LinkedIn or social media profile to attract more clients.',
    pain: 'People visit your profile but nobody ever contacts you.',
    logic: 'Analyzes your bio and headers to make them more professional.',
    category: 'Social',
    icon: <Smartphone size={20} />,
    keywords: ['linkedin', 'personal brand', 'conversion'],
    status: 'Coming Soon',
    savings: '10h research',
    protocol: 'Brand-Boost',
    model: 'Profile AI',
    cost: '$1.00',
    latency: 'Fast',
    depth: 'Expert Analysis',
    usageCount: 610
  },
  {
    id: 'viral-threader',
    name: 'Content Thread Maker',
    tagline: 'Turn long content into short posts',
    description: 'Converts long videos or articles into engaging social media threads automatically.',
    pain: 'Wasting hours trying to summarize content for social media.',
    logic: 'Picks out key points and turns them into viral post formats.',
    category: 'Marketing',
    icon: <Zap size={20} />,
    keywords: ['repurposing', 'content', 'growth'],
    status: 'Coming Soon',
    savings: '4h per piece',
    protocol: 'Content-Repurpose',
    model: 'Summarizer AI',
    cost: '$1.00',
    latency: 'Fast',
    depth: 'Key Insights',
    usageCount: 1540,
    isTrending: true
  },
  {
    id: 'comp-intel',
    name: 'Competitor Research',
    tagline: 'See what your competitors are doing',
    description: 'Research your competitors to find gaps in their pricing and marketing strategies.',
    pain: 'Losing clients to competitors you didn\'t even know existed.',
    logic: 'Scans the web to find competitor prices and service details.',
    category: 'Business',
    icon: <TrendingUp size={20} />,
    keywords: ['marketing', 'strategy', 'analysis'],
    status: 'Coming Soon',
    savings: '20h research',
    protocol: 'Market-Watch',
    model: 'Competitor AI',
    cost: '$1.00',
    latency: 'Deep Research',
    depth: 'Full Market Map',
    usageCount: 780
  },
  {
    id: 'qr-extractor',
    name: 'QR Code Reader',
    tagline: 'Read links from QR codes',
    description: 'Get links and info from any QR code using an image, screenshot, or your camera.',
    pain: 'Needing to use your phone just to open a QR link on your computer.',
    logic: 'Reads any QR code instantly using your browser camera or an uploaded image.',
    category: 'Engineering',
    icon: <Search size={20} />,
    keywords: ['qr', 'code', 'decoder', 'link'],
    status: 'Active',
    savings: 'Instant',
    protocol: 'Smart-Scan',
    model: 'QR-Vision',
    cost: 'FREE',
    isFree: true,
    latency: 'Instant',
    depth: 'Perfect Accuracy',
    usageCount: 1200,
    isTrending: true
  },
  {
    id: 'json-to-ts',
    name: 'TypeScript Generator',
    tagline: 'Turn data into clean code',
    description: 'Instantly convert complex data like JSON into clean TypeScript code for your projects.',
    pain: 'Hours spent manually typing and fixing code for data structures.',
    logic: 'Analyzes your data and writes the perfect code for you.',
    category: 'Engineering',
    icon: <Code size={20} />,
    keywords: ['dev', 'typescript', 'json'],
    status: 'Active',
    savings: 'Zero errors',
    protocol: 'Code-Writer',
    cost: 'FREE',
    isFree: true,
    latency: 'Instant',
    depth: 'Recursive Analysis',
    usageCount: 3200,
    isTrending: true
  },
  {
    id: 'compounding-engine',
    name: 'Wealth Builder',
    tagline: 'Plan your financial future',
    description: 'See how your money grows over time while accounting for inflation and monthly savings.',
    pain: 'Using simple bank calculators that don\'t account for real inflation.',
    logic: 'Uses precise financial math to show you what your money is actually worth in the future.',
    category: 'Finance',
    icon: <Calculator size={20} />,
    keywords: ['investment', 'savings', 'interest'],
    status: 'Active',
    savings: 'Accurate Planning',
    protocol: 'Finance-Math',
    cost: 'FREE',
    isFree: true,
    latency: 'Instant',
    depth: 'Inflation-Adjusted'
  },
  {
    id: 'tax-logic',
    name: 'Quick Tax Calculator',
    tagline: 'Estimate your taxes easily',
    description: 'Simple tax estimator for freelancers and people doing project-based work.',
    pain: 'Getting a huge unexpected tax bill at the end of the year.',
    logic: 'Calculates your tax based on the latest rules and your business expenses.',
    category: 'Finance',
    icon: <Percent size={20} />,
    keywords: ['accounting', 'tax', 'freelance'],
    status: 'Active',
    savings: 'Financial Peace',
    protocol: 'Tax-Pro',
    cost: 'FREE',
    isFree: true,
    latency: 'Instant',
    depth: 'Full Bracket Map'
  },
  {
    id: 'sip-forecaster',
    name: 'Investment Growth',
    tagline: 'Watch your savings grow',
    description: 'Visualize your savings over time with simple settings and easy-to-read charts.',
    pain: "Regular calculators don't account for salary hikes or rising costs.",
    logic: 'Shows your growth over 30 years with adjustable interest and savings.',
    category: 'Finance',
    icon: <TrendingUp size={20} />,
    keywords: ['investment', 'sip', 'mutual fund'],
    status: 'Active',
    savings: 'Wealth Tracking',
    protocol: 'Growth-Logic',
    cost: 'FREE',
    isFree: true,
    latency: 'Instant',
    depth: '30yr Chart'
  },
  {
    id: 'keyword-density',
    name: 'SEO Keyword Analyzer',
    tagline: 'Check your content SEO score',
    description: 'Analyze your article for keyword stuffing and readability to rank better on Google.',
    pain: "Not knowing why your article isn't ranking on search engines.",
    logic: 'Checks word usage and readability against search engine standards.',
    category: 'Marketing',
    icon: <Search size={20} />,
    keywords: ['seo', 'content', 'marketing'],
    status: 'Active',
    savings: 'Better Rankings',
    protocol: 'SEO-Scan',
    cost: 'FREE',
    isFree: true,
    latency: 'Fast',
    depth: 'Full Article Scan',
    usageCount: 410
  },
  {
    id: 'glassmorphism-gen',
    name: 'Glass Effect Designer',
    tagline: 'Create beautiful app designs',
    description: 'Design modern "frosted glass" styles for your website and get the code instantly.',
    pain: 'Endless CSS tweaking to get a modern "glass" look.',
    logic: 'A visual tool that generates perfect CSS for design effects.',
    category: 'Engineering',
    icon: <Sparkles size={20} />,
    keywords: ['ui', 'design', 'css'],
    status: 'Active',
    savings: 'Design Speed',
    protocol: 'UI-Gen',
    cost: 'FREE',
    isFree: true,
    latency: 'Instant',
    depth: 'All Browsers'
  },
  {
    id: 'base-transmuter',
    name: 'Number Converter',
    tagline: 'Convert numbers easily',
    description: 'Convert numbers between formats like Decimal, Hex, and Binary with high precision.',
    pain: 'Using confusing online converters that are slow and inaccurate.',
    logic: 'High-precision conversion for any size of number.',
    category: 'Engineering',
    icon: <Repeat size={20} />,
    keywords: ['developer', 'binary', 'hex'],
    status: 'Active',
    savings: 'No Math Errors',
    protocol: 'Logic-Pro',
    cost: 'FREE',
    isFree: true,
    latency: 'Instant',
    depth: 'Unlimited Precision'
  },
  {
    id: 'amortization-scalpel',
    name: 'Loan Repayment Tracker',
    tagline: 'See how to pay off debt faster',
    description: 'Visualize how extra payments on your loan can save you thousands in interest.',
    pain: 'Paying too much in interest over the life of your loan.',
    logic: 'Calculates the exact impact of extra payments on your debt.',
    category: 'Finance',
    icon: <Activity size={20} />,
    keywords: ['debt', 'mortgage', 'loan'],
    status: 'Coming Soon',
    savings: 'Save Interest',
    protocol: 'Debt-Logic',
    cost: 'FREE',
    isFree: true,
    latency: 'Instant',
    depth: 'Full Loan Map'
  },
  {
    id: 'gst-global',
    name: 'Global Tax Calculator',
    tagline: 'Calculate GST/VAT globally',
    description: 'Instantly calculate taxes for 50+ countries with current tax rates.',
    pain: 'Manually calculating taxes for international clients.',
    logic: 'Uses the latest tax rates for every major country.',
    category: 'Finance',
    icon: <Globe size={20} />,
    keywords: ['tax', 'accounting', 'invoice'],
    status: 'Coming Soon',
    savings: 'Accuracy',
    protocol: 'Global-Tax',
    cost: 'FREE',
    isFree: true,
    latency: 'Instant',
    depth: '50+ Countries'
  },
  {
    id: 'utm-builder',
    name: 'Marketing Link Builder',
    tagline: 'Create tracking links in bulk',
    description: 'Generate many tracking links (UTMs) at once for your marketing campaigns.',
    pain: 'Creating tracking links one-by-one is slow and boring.',
    logic: 'Automatically builds multiple marketing links from your settings.',
    category: 'Marketing',
    icon: <LayoutList size={20} />,
    keywords: ['marketing', 'tracking', 'ads'],
    status: 'Coming Soon',
    savings: '2h per campaign',
    protocol: 'Link-Build',
    cost: 'FREE',
    isFree: true,
    latency: 'Instant',
    depth: 'Bulk Export'
  },
  {
    id: 'contrast-auditor',
    name: 'Design Accessibility Tool',
    tagline: 'Check if your design is readable',
    description: 'Check your design colors to make sure everyone can read your website easily.',
    pain: 'Designing websites that look good but are hard to read.',
    logic: 'Checks your colors against international accessibility standards.',
    category: 'Engineering',
    icon: <Users size={20} />,
    keywords: ['accessibility', 'design', 'ui'],
    status: 'Coming Soon',
    savings: 'Readability',
    protocol: 'A11y-Check',
    cost: 'FREE',
    isFree: true,
    latency: 'Instant',
    depth: 'Global Standards'
  },
  {
    id: 'currency-arbitrage',
    name: 'Best Exchange Rate Finder',
    tagline: 'Save money on currency exchange',
    description: 'Find the best exchange rates across different sources in real-time.',
    pain: 'Losing money on bad currency exchange rates.',
    logic: 'Checks multiple sources to find you the best rate right now.',
    category: 'Finance',
    icon: <Repeat size={20} />,
    keywords: ['forex', 'arbitrage', 'finance'],
    status: 'Coming Soon',
    savings: '1-2% per txn',
    protocol: 'Rate-Check',
    cost: 'FREE',
    isFree: true,
    latency: 'Fast',
    depth: 'Live Rates'
  },
  {
    id: 'crypto-gas',
    name: 'Crypto Fee Tracker',
    tagline: 'Save on crypto transaction fees',
    description: 'Track real-time network fees (gas) for Ethereum and other networks to save money.',
    pain: 'Paying high fees for crypto transfers unnecessarily.',
    logic: 'Monitors blockchain networks for the cheapest times to transfer.',
    category: 'Engineering',
    icon: <Zap size={20} />,
    keywords: ['crypto', 'eth', 'gas'],
    status: 'Coming Soon',
    savings: '80% costs',
    protocol: 'Fee-Watch',
    cost: 'FREE',
    isFree: true,
    latency: 'Fast',
    depth: 'All Networks'
  },
  {
    id: 'mortgage-break-even',
    name: 'Refinance Calculator',
    tagline: 'See if refinancing saves money',
    description: 'Calculate exactly when your mortgage refinance savings will cover the costs.',
    pain: 'Refinancing without knowing if it actually saves you money.',
    logic: 'Compares your current loan with a new one to find your savings.',
    category: 'Finance',
    icon: <Clock size={20} />,
    keywords: ['mortgage', 'refinance', 'loans'],
    status: 'Coming Soon',
    savings: 'Financial Certainty',
    protocol: 'Loan-Logic',
    cost: 'FREE',
    isFree: true,
    latency: 'Instant',
    depth: '30yr Analysis'
  },
  {
    id: 'drip-visualizer',
    name: 'Investment Snowball Tool',
    tagline: 'See your investment grow over time',
    description: 'Visualize how reinvesting your earnings speeds up your wealth building.',
    pain: 'Underestimating how small reinvestments grow into large amounts.',
    logic: 'Shows the long-term power of reinvesting your investment income.',
    category: 'Finance',
    icon: <TrendingUp size={20} />,
    keywords: ['dividends', 'stocks', 'compounding'],
    status: 'Coming Soon',
    savings: 'Long-term clarity',
    protocol: 'Wealth-Map',
    cost: 'FREE',
    isFree: true,
    latency: 'Fast',
    depth: 'Snowball Effect'
  }
];
